### PR TITLE
Comlink assets conventions

### PR DESCRIPTION
**Pull request by freaz**
This PR:

- renames SuperfaceClient to **OneClient**
- rename sdkAuthToken to **token**
- uses **.profile** , **.provider.json**, **.map.js** file extensions
- documents expected Comlink file structure
- removes Result object as perform return in  Node.js client
- renames maps examples to more accurate comlinks examples
- default folder for Comlinks is **superface** - I don't like it as it is now only place taking about superface 🤷‍♂️

### CODE REVIEW

**Comment by zdne** [comment]
First Saturday morning thoughts: I'd keep .js (for convenience I guess) and I would rename both SDK and the main class to OneClient 🤯

**Comment by zdne** [comment]
would love to hear @martyndavies take on this

**Comment by freaz** [comment]
So the constraint to keep same interface as in OneSDK 1.x and 2.x doesn't apply anymore? Because I'd like to at least remove the Result object of perform, in favor of throwing exceptions and returning result.

**Comment by martyndavies** [comment]
Here's my take. We should keep using `.suma.js` in the naming convention so there's always clarity about where the code came from and what it relates to. It allows us something specific to point at in documentation, removes the chances of accidental use elsewhere in an app through misnaming, and helps developer teams identify Superface generated code over their own, because they can always as "where does this `.suma.js` stuff come from".

**Pull request merged**
