### PR TITLE
feat: build-a-core

### PR DESCRIPTION
**Pull request by TheEdward162**
build-a-core is a script which allows us to build any[1] commit of the one-sdk repo against any rust toolchain, wasi-sdk version and wasm-opt version, allows configuring the Cargo profile for the build, the wasm-opt settings and even allows building Rust std as a part of the build (only works with a nightly toolchain though). It does all of this in Docker so it makes use of cache and isolation.

This will allow us to experiment with these build configurations, for example for comparing binary size, performance implications of some decisions and more. My expectation is that for each experiment we will build a small wrapper on top of build-a-core to build the appropriate candidates and compare them by the metric we care about.

Also removes docker from the Makefile - I feel like we weren't using it and build-a-core superseeds it. Dockerfiles for wasi-sdk and binaryen now live in `scripts/` and can be used to build any ref of these projects (wasi-sdk doesn't ship for aarch64-linux and binaryen is outdated in debian/ubuntu repos, so it's good to build the latest release).

[1] of course not any, but in general an arbitrary commit where the repo is in some sensible shape to be built

### CODE REVIEW

**Review by freaz — APPROVED** [review]
Thanks, impressive 👍

**Review by freaz — COMMENTED** [review]
Just realised, CONTRIBUTION.md contains mention of docker build. It should be removed.

**Comment by TheEdward162** [comment]
Updated the doc + rebased on main

**Review by freaz — APPROVED** [review]
👌

**Pull request merged**
